telegram:
  token: "7933867253:AAFDSRhNmoYzgPfVA8ZvldAfRZgSU9yfoDY"

  chat_id: -4244608457

  admin_ids: 
    - 771387372
    - 1005303293
    - 1311181246
    - 1797658864
    - 1514282558
    - 6287270770
    - 6981739249
    - 932802187
    - 796508150

database:
  host: "192.168.107.50"
  port: 3333
  user: "ticketing"
  password: "mySqlBOTtICkETing@2k25"
  database: "ticketing"
  tables: # (Don't change it)
    - ticketsv4
    - ticket_messagesv4
    - banned_users
    - handlers

timezone: "Asia/Jakarta"

messages:
  custom_welcome_message: |
    ğŸ™ Selamat datang di *Binstro Support System*

    Terima kasih telah menghubungi kami. Untuk membantu Anda dengan lebih baik:

    ğŸ“ Setiap pesan yang Anda kirimkan akan secara otomatis dibuatkan tiket
    â±ï¸ Tim kami akan merespons secepatnya
    âœ… Mohon jelaskan keluhan atau pertanyaan Anda secara detail

    Silakan sampaikan keluhan atau pertanyaan Anda sekarang.

  reply_message_private: |
    ğŸ« *Ticket #{ticket_id}*

    Terima kasih ğŸ™ telah menghubungi *Binstro Support*.

    âœ… Pesan Anda telah kami terima dan akan segera diproses.
    ğŸ“‹ Tim kami akan menindaklanjuti dalam waktu 1x24 jam kerja.

  urgent_issue_messagge: |
    âš ï¸ *Laporan Urgent*

    Kami memahami urgensi laporan Anda. Tim kami akan memprioritaskan 
    penanganan masalah ini dengan response time 4 jam kerja.
    Mohon tunggu sebentar, tim kami akan segera menghubungi Anda.

  template_ticket_message: |
    ğŸ« *Ticket* #{ticket_id}

    ğŸ‘¤ `{user_name}` (@{username})
    â° `{timestamp}`

    ğŸ“ Details:
    {message}
  
  template_open_ticket_in_user: |
    âš ï¸ *Perhatian!* âš ï¸
    Anda bukan administrator sistem dan tidak memiliki akses untuk menjalankan perintah pada bot ini.
    Silakan hubungi administrator jika Anda memerlukan bantuan lebih lanjut.
    Terima kasih atas pengertian Anda! ğŸ¤–âœ¨

  template_open_ticket_in_admin: |
    ğŸ« *Open Tickets*:
      {list_open_tickets}
  
  template_link_open_ticket: |
    â€¢ #{ticket_id} *[ {user_full_name} ]* ( `{user_id}` )
        â†³ {relative_time} â‡’ [Go to msg]({link_message})

  template_open_ticket_not_found: |
    ğŸš« Tidak ada tiket yang tersedia untuk diambil saat ini.
    Coba lagi nanti atau periksa antrian tiket secara berkala.